title: NewsToon
description: 뉴스를 한 편의 웹툰처럼
url: "https://sosim13mac.github.io"
baseurl: "/NewsToon"
lang: ko-KR
timezone: Asia/Seoul
markdown: kramdown
permalink: /news/:year/:month/:day/:title/
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: NewsToon
